# Site settings
title: M-Lab
email: support@measurementlab.net
excerpt_separator: <!--more-->

# Default baseurl used for gh-pages branches.
# Travis will change it to "" before deploying.
# For local development pass in blank baseurl to simulate prod-like environment: 
# $ jekyll serve --baseurl
baseurl: "/m-lab.github.io"

# Build settings
permalink: "/blog/:title/"
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock

# Display blog posts even if they're future-dated.
future: true

# Gems
gems: ['jekyll-paginate', 'jekyll-feed']
paginate: 1
paginate_path: "/blog/page/:num"

# HTML Compression settings
compress_html:
  clippings: [ ]
  blanklines: false
  profile: false
